input :
    syslog:
        addr : "0.0.0.0:8055"


filter :
     
output:
    elasticsearch :
        index : asset_syslog
        host : [es1,es2,es3,es4,es5]
        bulk : 10000
        index_by_day : true
        mapping_load : "./dynamic_templates_string_to_keyword.json"
     
