input :
    kafka :
        addr : ["10.0.24.42:9092"]
        topic : topic_mdr_email
        partition : 0-5

filter :
    json :
        source : "Message"
        geoip : 
            - [src_ipv4, SrcIP_Geo]
            - [dst_ipv4, DstIP_Geo]

 
output:
    elasticsearch :
        index: gbeat_dpi_mdr_email
        index_by_day : true
        host : [10.0.24.42]
        bulk : 10000
        mapping_load : "/opt/dynamic_templates_string_to_keyword.json"

