
tlv :
    msg_type : 0
    proto_type : 0
    tlv_config:
        - ["XDR_ID",1,s]
        - ["Procedure_Start_Time",2,s]
        - ["Flow_Continue_Time",3, s]
        - ["Procedure_End_Time",4,s]
        - ["Flow_end_reason",5,s]

        - ["Link_operator_name",30, s]
        - ["Link_net_short_name",31,s]
        - ["Link_collect_place",32, s]
        - ["Link_dev_nu",33,s]
        - ["Link_equ_type",34,s]
        - ["Link_equ_slot",35,s]
        - ["Link_link_type",36]
        - ["Link_inface_speed_type",37,s]
        - ["Link_input_type",38]
        - ["Link_link_no",39]
        - ["Link_link_direc",40]
        - ["ETH_src_mac",60,s]
        - ["ETH_dst_mac",61,s]
        - ["ETH_out_vlan",62]
        - ["ETH_inner_vlan",63]
        - ["IP_ip_ver",80,s]
        - ["IP_ip_dscp",81]
        - ["IP_ip_len",82]
        - ["IP_frag_id",83]
        - ["IP_more_frag_flag",84]
        - ["IP_enable_frag",85]
        - ["IP_first_offset",86]
        - ["IP_ip_ttl",87]
        - ["IP_ipv6_ext",88]
        - ["tunnel_num_1",130]
        - ["tunnel_type_1",131]
        - ["tunnel_ip_type_1",132]
        - ["tunnel_sip_1",133]
        - ["tunnel_src128_1",134]
        - ["tunnel_head_info_1",135]
        - ["tunnel_dest_1",136]
        - ["tunnel_dst128_1",137]
        - ["tunnel_sport_1",138]
        - ["tunnel_dport_1",139]
        - ["tunnel_L4_ptoto_1",140]
        - ["tunnel_num_2",160]
        - ["tunnel_type_2",161]
        - ["tunnel_ip_type_2",162]
        - ["tunnel_sip_2",163]
        - ["tunnel_src128_2",164]
        - ["tunnel_head_info_2",165]
        - ["tunnel_dest_2",166]
        - ["tunnel_dst128_2",167]
        - ["tunnel_sport_2",168]
        - ["tunnel_dport_2",169]
        - ["tunnel_L4_ptoto_2",170]
        - ["HASH_FLOW_ipv4_hash",180]
        - ["HASH_FLOW_ipv6_hash",181]
        - ["HASH_FLOW_acl_rul_id",182]
        - ["HASH_FLOW_out_port_group_id",183]
        - ["HASH_FLOW_buss_id",184,s]
        - ["TCP_seq",200]
        - ["TCP_next_seq",201]
        - ["TCP_tcp_head_len",202]
        - ["TCP_tcp_res_flag",203]
        - ["TCP_tcp_ctl_flag",204]
        - ["TCP_tcp_check_sum",206]
        - ["TCP_urg_flag",207]
        - ["ACCESS_access_type",250]
        - ["ACCESS_access_attribute",251]
        - ["ACCESS_country",252]
        - ["ACCESS_province",253]
        - ["ACCESS_city",254]
        - ["ACCESS_county",255]
        - ["ACCESS_town",256]
        - ["ACCESS_street",257]
        - ["ACCESS_s_GPS_longitude",258]
        - ["ACCESS_c_GPS_longitude",259]
        - ["ACCESS_s_GPS_latitude",260]
        - ["ACCESS_c_GPS_latitude",261]
        - ["ACCESS_s_GPS_height",262]
        - ["ACCESS_c_GPS_height",263]
        - ["ACCESS_coordinate",264]
        - ["STAT_unknowe_flag",300,s]
        - ["STAT_up_bps",305]
        - ["STAT_dn_bps",306]
        - ["STAT_up_pps",307]
        - ["STAT_dn_pps",308]
        - ["RELATION_hit_rul_log_id",390]
        - ["RELATION_bear_proto_log_id",391]
        - ["RELATION_app_proto_log_id",392]
        - ["HIT_buss_id",250]
        - ["HIT_rul_type",251]
        - ["HIT_rul_group_id",252]
        - ["HIT_pcap_index",253]
        - ["HIT_direct",254]
        - ["HIT_hit_num",255]
        - ["HIT_out_port_group_id",256]
        - ["HIT_HOST",300,s]
        - ["HIT_URI",301,s]
        - ["HIT_User-Agent",302,s]
        - ["HIT_HTTP_Request_type",303,s]
        - ["HIT_SNI",350,s]
        - ["HIT_dns_Domain_Name",380,s]
        - ["HIT_dns_QUERY_TYPE",381]
        - ["HIT_dns_IP_Addr",382]
        - ["HIT_dns_match_method",383]
        - ["HIT_Email_Sender",400]
        - ["HIT_Email_Receiver",401]
        - ["HIT_Email_CCer",402]
        - ["HIT_Email_Theme",403]

tlv_common :
    tlv_config:
        - ["USER_IPv4",100,s]
        - ["USER_IPv6",101,s]
        - ["User_Port",104,s]
        - ["L4_protocal",106]
        - ["App_Server_IP_IPv4",102,s]
        - ["App_Server_IP_IPv6",103,s]
        - ["App_Server_Port",105,s]

        - ["UL_Data",302,l]
        - ["DL_Data",304,l]
        - ["UL_IP_Packet",301,l]
        - ["DL_IP_Packet",303,l]
        - ["UL_Disorder_IP_Packet",208]
        - ["DL_Disorder_IP_Packet",209]
        - ["UL_Retrans_IP_Packet",210]
        - ["DL_Retrans_IP_Packet",211]
        - ["TCP_Response_Time",212,s]
        - ["Window",205]

        - ["IDFY_app_type_name",50,s]
        - ["IDFY_app_type_code",51]
        - ["IDFY_APP_name",52,s]
        - ["IDFY_APP_code",53,s]
        - ["IDFY_app_proto_ID",54,s]
        - ["IDFY_app_uni_proro_code",55,s]




