
input :
    kafka :
        addr : ["10.0.24.42:9092"]
        topic : topic_syslog_apt
        partition : 0-5

filter :
    json :
        source : "Message"


output:
    elasticsearch :
        index : gbeat_sunyainfo_apt
        host : [10.0.24.42]
        bulk : 10000
        mapping_load : "/opt/dynamic_templates_string_to_keyword.json" 
