input :
    syslog:
        addr : "0.0.0.0:8055"


filter :
     
output:
    elasticsearch :
        index : asset_syslog
        host : [10.0.24.44:9201,10.0.24.44:9202,10.0.24.44:9203]
        bulk : 10000
        index_by_day : true
        mapping_load : "/opt/dynamic_templates_string_to_keyword.json"
     
