input :
    syslog:
        addr : "0.0.0.0:9040"


filter :
    json :
        source : "Message"
 
output:
    kafka:
        host: ["10.0.24.42:9092"]
        topic: topic_syslog_apt
        max_message_bytes : 100000000
