
input :
    tcp :
        addr : 0.0.0.0:9012
        type : dpi_xdr_http
        fields :
            input_type : log
            tag : dpi_xdr_http
 
filter :
    mutate :
        split : Message,|

        split_fields :
            0 : Length
            1 : LocalProvince
            2 : LocalCity
            3 : OwnerProvince
            4 : OwnerCity
            5 : RoamingType
            6 : Interface
            7 : XDRID
            8 : AppTypeCode
            9 : ProcedureStartTime
            10 : ProcedureEndTime
            11 : Longitude
            12 : Latitude
            13 : Height
            14 : Coordinatesystem
            15 : ProtocolType
            16 : AppType
            17 : AppSub-type
            18 : AppContent
            19 : AppStatus
            20 : IPaddresstype
            21 : USER_IPv4
            22 : USER_IPv6
            23 : UserPort
            24 : L4protocal
            25 : AppServerIP_IPv4
            26 : AppServerIP_IPv6
            27 : AppServerPort
            28 : ULData
            29 : DLData
            30 : ULIPPacket
            31 : DLIPPacket
            32 : Updura
            33 : Downdura
            34 : ULDisorderIPPacket
            35 : DLDisorderIPPacket
            36 : ULRetransIPPacket
            37 : DLRetransIPPacket
            38 : TCPResponseTime
            39 : TCPACKTime
            40 : UL_IP_FRAG_PACKETS
            41 : DL_IP_FRAG_PACKETS
            42 : FirstReqTime
            43 : FirstResponseTime
            44 : Window
            45 : MSS
            46 : TCPSYNNum
            47 : TCPStatus
            48 : SessionEnd
            49 : TCPSYNACKNum
            50 : TCPACKNum
            51 : TCP12HandshakeStatus
            52 : TCP23HandshakeStatus
            53 : ULProbeID
            54 : ULLINKIndex
            55 : DLProbeID
            56 : DLLINKIndex
            57 : TransactionID
            58 : FlowControl
            59 : UL_AVG_RTT
            60 : DL_AVG_RTT
            61 : UserAccount
            62 : ReferXDRID
            63 : Rule_source
            64 : HTTPVersion           
            65 : MessageType
            66 : MessageStatus
            67 : FirstHTTPResponseTime
            68 : LastContentPacketTime
            69 : LastACKTime
            70 : HOSTLength
            71 : HOST
            72 : URILength
            73 : URI
            74 : XOnlineHostLength
            75 : XOnlineHost
            76 : UserAgentLength
            77 : UserAgent
            78 : HTTPContentType     
            79 : ReferURILength
            80 : ReferURI
            81 : CookieLength
            82 : Cookie
            83 : ContentLength
            84 : Keyword
            85 : ServiceBehaviorFlag
            86 : ServiceCompFlag
            87 : ServiceTime
            88 : IE
            89 : Portal
            90 : LocationLength
            91 : Location
            92 : FirstRequest
            93 : HTTPUserAccount
            94 : URIType
            95 : URISubType

        convert : 
            - [Length,              int]
            - [Interface,           int]
            - [ProcedureStartTime,  int]
            - [ProcedureEndTime,    int]
            - [ULData,              int]
            - [DLData,              int]
            - [ULIPPacket,          int]
            - [DLIPPacket,          int]
            - [ULDisorderIPPacket,  int]
            - [DLDisorderIPPacket,  int]
            - [ULRetransIPPacket,   int]
            - [DLRetransIPPacket,   int]
            - [TCPResponseTime,     int]
            - [TCPACKTime,          int]
            - [UL_IP_FRAG_PACKETS,  int]
            - [DL_IP_FRAG_PACKETS,  int]
            - [FirstReqTime,        int]
            - [FirstResponseTime,   int]
            - [Window,              int]
            - [MSS,                 int]
            - [TCPSYNNum,           int]
            - [TCPSYNACKNum,        int]
            - [TCPACKNum,           int]
            - [UL_AVG_RTT,          int]
            - [DL_AVG_RTT,          int]
            - [HOSTLength,          int]
            - [URILength,           int] 
            - [XOnlineHostLength,   int]
            - [UserAgentLength,     int]
            - [ReferURILength,      int]
            - [CookieLength,        int]
            - [LocationLength,      int]

output:
    kafka:
        host: [10.0.24.42:9092]
        topic: dpi_xdr
        max_message_bytes : 100000000


