
input :
    tcp: 
        addr : "0.0.0.0:9051"


filter :
    json :
        source : "Message"
 
output:
    kafka:
        host: ["10.0.24.42:9092"]
        topic: topic_dpi_mdr_im_wechat
        max_message_bytes : 100000000
