
input :
    kafka :
        addr : ["10.0.24.42:9092"]
        topic : dpi_log
        partition : 0-5

filter :
    json :
        source : "Message"
 
output:
    elasticsearch :
        index_prefix : gbeat_dpi_mdr_
        index_var : data_type
        index_by_day : true
        host : ["10.0.24.42:9200"]
        bulk : 10000




