
input :
    kafka :
        addr : ["10.0.24.42:9092"]
        topic : topic_dpi_xdr_com
        #topic : dpi_filerevert
        partition : 0-5 
        type : dpi_xdr_com

filter :
   # json :
    #    source : "Message"

 
output:
#    elasticsearch : 
 #       index : aa
  #      host : ["10.0.24.128:9200"]
   #     bulk : 10000
    #    sendmode : polling




