
input :
    kafka :
        addr : ["10.0.24.42:9092"]
        topic : dpi_log
        partition : 0-5


filter :
    json :
        source : "Message"
 
 
output:
    elasticsearch :
        index_prefix : gbeat_dpilog_
        index_var : data_type
        host : ["10.0.24.42:9200"]
        bulk : 10000


