
input :
    file:
        paths: ["/Users/handawei/g/c/.log"]
        type : "test"
        #read_mode : "end"
 
filter :


output:  
    elasticsearch : 
        index : tt
        host : [10.0.24.125:9201]
        index_by_day : true
     




