input :
    syslog:
        addr : "0.0.0.0:524"
        fields :
            tag : syslog


filter :
    json :
        source : "Message"
 
output:
    kafka:
        host: ["10.0.24.42:9092"]
        topic: topic_syslog
        max_message_bytes : 100000000
