
input :
    tcp:
        addr : "0.0.0.0:8000"
        auto_newlines : False
        performance_mode : true

filter :
    json :
        source : "Message"
 
output:
    elasticsearch : 
        index : oa
        id : itcode
        host : [10.0.24.128:9200]
        bulk : 10000


