input :
    syslog:
        addr : "0.0.0.0:8055"


filter :
     
output:
    elasticsearch :
        index : asset_syslog
        host : [10.12.0.230:9201,10.12.0.230:9202,10.12.0.230:9203,10.12.0.230:9204,10.12.0.230:9205]
        bulk : 10000
        index_by_day : true
        mapping_load : "./dynamic_templates_string_to_keyword.json"
     
