
input :
    tcp: 
        addr : "0.0.0.0:8030"


filter :
    json :
        source : "Message"
 
 
output:
    elasticsearch :
        index_prefix : gbeat_dpi_log_
        index_var : data_type
        host : [es1,es2,es3,es4,es5]
        mapping_load : "./dynamic_templates_string_to_keyword.json"
        bulk : 10000


